server:
  port: 8080
#  servlet:
#    session: 
#     cookie:
#        name: SSO-CLIENT1
spring:
  application:
    name: microservice-sso-client1
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/microservice-sso?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}   
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 12345
      access-token-uri: http://localhost:9999/oauth/token  # 获取access token接口
      user-authorization-uri: http://localhost:9999/oauth/authorize  # 获取Authorization Code接口
      registered-redirect-uri: http://127.0.0.1:8080/
    resource:
      user-info-uri: http://localhost:9999/user/me
      token-info-uri: http://localhost:9999/oauth/check_token # 验证token的接口
#      jwt:
#        key-uri: http://localhost:9999/oauth/token_key #解析jwt令牌所需要密钥的地址
    
      