server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false      # 关闭自我保护
    eviction-interval-timer-in-ms: 5000  # 清理服务
  client: 
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false    #是否注册自身到eureka服务器
    fetch-registry: false          #是否从eureka服务器获取注册信息
# 日志配置:       
logging: 
  level: 
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    cn.segema.cloud.discovery: ERROR
  file: /data/logs/wemall-springcloud/discovery.log       