spring:
  application:
    name: microservice-common
  aop:
    auto: true
    proxy-target-class: true  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE