server:
  port: 8081
spring:
  application:
    name: microservice-sso-client2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservice_sso?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging: 
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
security:
  oauth2:
    client:
      client-id: client2
      client-secret: client2
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource: 
       token-info-uri: http://localhost:9999/oauth/check_token  # 验证token的接口
#      user-info-uri: http://localhost:9999/user/me
#      jwt:
#        key-uri: http://localhost:9999/oauth/token_key

    
      