server:
  port: 8443
spring: 
  application:
    name: microservice-sso-server
  datasource:                       
    url: jdbc:mysql://127.0.0.1:3306/microservice_sso?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root  
    password: root  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      show-sql: true  
# redis配置:    
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool: 
       max-active: 100
       max-idle: 100
       min-idle: 50
       max-wait: 6000
    timeout: 1000 

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    cn.segema.cloud.sso.server: ERROR
  file: /data/logs/microservice-sso/sso-server.log      
       
eureka: 
  instance:
    hostname: sso-server
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

# SSO配置:      
sso: 
  security: 
    oauth2:
      storeType: jwt     
    jwt: 
      signingKey: segema1234567890   
justauth:
  enabled: true
  type:
    WECHAT_MP:
      client-id: wx5e8bd85c8a0e3ad91
      client-secret: 179b5b9cef5007c49d38971736d0562d1
      redirect-uri: http://www.fengtuwei.com/v1/sso-server/oauth/callback/WECHAT_MP
    WECHAT_ENTERPRISE:
      client-id: ww58**********6fbc
      client-secret: 8G6PCr0****************************yzaPc78
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/callback/WECHAT_ENTERPRISE
      agent-id: 1000002
    DINGTALK:
      client-id: ding*************cl3
      client-secret: fz_NeJh9S***************************************XduEx4nyG8ZFiMD
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/callback/DINGTALK
    GITHUB:
      client-id: 3818ca63632a5c6863831
      client-secret: 9d4e8c206ab9426acc7a61a466503952ef30d2f21
      redirect-uri: http://www.fengtuwei.com/v1/sso-server/oauth/callback/GITHUB  
  cache:
    type: default
    prefix: 'demo::'
    timeout: 1h
