server:
  port: 8081
  servlet:
    session:
      cookie:
        name: SSO-CLIENT2
spring:
  application:
    name: microservice-sso-client2
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wemall_springcloud?useUnicode=true&amp;characterEncoding=utf8
    username: fengtuwei
    password: fengtuwei
logging: 
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
security:
  oauth2:
    client:
      client-id: client2
      client-secret: 12345
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource: 
      user-info-uri: http://localhost:9999/user/me
#      token-info-uri: http://localhost:9999/oauth/check_token # 验证token的接口
#      jwt:
#        key-uri: http://localhost:9999/oauth/token_key

    
      